### ISSUE TITLE
Support bit-level initialization tracking.

### ISSUE THREAD

**Issue by mheinsen** [seec-team/seec#16]
_From @mheinsen on March 15, 2013 2:31_

I think that this should proceed as follows:
1. Update shadow memory tracking to be allocation-based rather than the old fragment-based system (recreated memory was updated way back in 97b8557fca6edaaa967b0528e3a69ca36774c8a8).
2. Implement methods to retrieve/set the shadow state of memory that can be used by instrumented code and interceptors.
3. Update the instrumentation to propagate uninitialized bits through instructions.

In the long term, it would be nice to have a large block of shadow memory so that determining the location of the shadow memory for any particular byte was a simple operation (a la Memcheck, MemorySanitizer, etc.)

_Copied from original issue: mheinsen/seec#9_

**Comment by mheinsen** [comment]
- [x] Update shadow memory tracking to be allocation-based rather than the old fragment-based system (done in 6d04037312ccadf6e24e63e7a986f1cf92cf0dfb)
- [ ] Implement methods to retrieve/set the shadow state of memory that can be used by instrumented code and interceptors.
- [ ] Update the instrumentation to propagate uninitialized bits through instructions.
